name: escape_game_kit_example
description: A small demo of EscapeGameKit.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  escape_game_kit:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  just_audio: ^0.9.20
  just_audio_libwinmedia: ^0.0.4
  qr_flutter: ^4.0.0
  window_manager: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/backgrounds/
    - assets/glitch/
    - assets/interactables/
