name: escape_game_kit_example
description: A small demo of EscapeGameKit.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  escape_game_kit:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.8
  window_manager: ^0.3.0
  just_audio: ^0.9.31
  just_audio_windows: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf
  assets:
    - assets/
    - assets/backgrounds/
    - assets/fonts/
    - assets/glitch/
    - assets/interactables/
    - assets/objects/
    - assets/padlocks/
