name: escape_game_kit
description: A kit for creating escape games using Flutter.
version: 1.0.0
homepage: https://github.com/Skyost/EscapeGameKit

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  animate_do: ^2.1.0
  avatar_glow: ^2.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.4
