import 'package:animate_do/animate_do.dart';
import 'package:escape_game_kit/src/game/room/interactables/render_settings.dart';
import 'package:flutter/material.dart';

/// Allows to render an [InteractableAnimation] thanks to `animate_do`.
class InteractableAnimationWidget extends StatelessWidget {
  /// The animation.
  final InteractableAnimation? animation;

  /// The child widget.
  final Widget child;

  /// The animation controller.
  final Function(AnimationController)? controller;

  /// Whether to animate.
  final bool animate;

  /// Creates a new [InteractableAnimationWidget] instance.
  const InteractableAnimationWidget({
    super.key,
    required this.animation,
    required this.child,
    this.controller,
    this.animate = true,
  });

  @override
  Widget build(BuildContext context) => animation == null
      ? child
      : switch (animation!.type) {
          InteractableAnimationType.fadeIn => FadeIn(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            child: child,
          ),
          InteractableAnimationType.fadeInDown => FadeInDown(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeInDownBig => FadeInDownBig(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeInUp => FadeInUp(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeInUpBig => FadeInUpBig(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeInLeft => FadeInLeft(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeInLeftBig => FadeInLeftBig(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeInRight => FadeInRight(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeInRightBig => FadeInRightBig(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeOut => FadeOut(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            child: child,
          ),
          InteractableAnimationType.fadeOutDown => FadeOutDown(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeOutDownBig => FadeOutDownBig(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeOutUp => FadeOutUp(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeOutUpBig => FadeOutUpBig(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeOutLeft => FadeOutLeft(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeOutLeftBig => FadeOutLeftBig(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeOutRight => FadeOutRight(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.fadeOutRightBig => FadeOutRightBig(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.bounceInDown => BounceInDown(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.bounceInUp => BounceInUp(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.bounceInLeft => BounceInLeft(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.bounceInRight => BounceInRight(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.elasticIn => ElasticIn(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            child: child,
          ),
          InteractableAnimationType.elasticInDown => ElasticInDown(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.elasticInUp => ElasticInUp(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.elasticInLeft => ElasticInLeft(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.elasticInRight => ElasticInRight(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.slideInDown => SlideInDown(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.slideInUp => SlideInUp(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.slideInLeft => SlideInLeft(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.slideInRight => SlideInRight(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.flipInX => FlipInX(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            child: child,
          ),
          InteractableAnimationType.flipInY => FlipInY(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            child: child,
          ),
          InteractableAnimationType.zoomIn => ZoomIn(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.zoomOut => ZoomOut(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            child: child,
          ),
          InteractableAnimationType.jelloIn => JelloIn(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            child: child,
          ),
          InteractableAnimationType.bounce => Bounce(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            from: animation!.from,
            infinite: animation!.infinite,
            child: child,
          ),
          InteractableAnimationType.flash => Flash(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            infinite: animation!.infinite,
            child: child,
          ),
          InteractableAnimationType.pulse => Pulse(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            infinite: animation!.infinite,
            child: child,
          ),
          InteractableAnimationType.swing => Swing(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            infinite: animation!.infinite,
            child: child,
          ),
          InteractableAnimationType.spin => Spin(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            infinite: animation!.infinite,
            child: child,
          ),
          InteractableAnimationType.spinPerfect => SpinPerfect(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            infinite: animation!.infinite,
            child: child,
          ),
          InteractableAnimationType.dance => Dance(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            infinite: animation!.infinite,
            child: child,
          ),
          InteractableAnimationType.roulette => Roulette(
            duration: animation!.duration,
            delay: animation!.delay,
            controller: controller,
            manualTrigger: animation!.manualTrigger,
            animate: animate,
            infinite: animation!.infinite,
            child: child,
          ),
        };
}
